<?php 
	$Death_prophet_intro = "<p>Super tank in 6.51, that was a time for push intelligence: 'dp, tinker, ss, nec'. That was a time that heart's regeneration will not be stopped by hero's attack and blood stone had far better regen effect. After a team fight she will likely stand there with full hp and give you a charming smile.</p>
		<p>You'd better be careful when chasing dp, you are so easy to be skilled by her Exorcism.</p>";

	$Faceless_void_intro = "<p>Only chrono that matters!</p><p>A good chrono can change the whole game, meanwhile a bad one will bury it. Recently everyone loves fv, he has late game potential, especially when he has a refresher, he loves pure damage, madness, mjollnir, daedalus are his favorite, with diffusal blade and manta he is also a perfect choice again super Medusa. His good companions inlude Invoker, Mirana, Sand King and Skywrath Mage, those combos are too shiny and I dare not star at the monitor.</p>";

	$Lina_intro = "<p>Lina is definitely the most sexy female in Dota family with an explosive temper like fire.</p><p>She is also one of the best nuker. Back to 6.48, where blink is everything, you kill someone within a combo, or you will never have a change if you do not possess a blink dagger. Everyone back then was crazy about flexibility and immediate damage. With blink Lina can cause tons of damage only by herself and with a very short cool down of her skills, next round murder will come soon. Nowadays Lina joins the Fuck-off BKB club, aftering carrying Aghanim BKB will be nothing but some gold paper in front of Lina</p>";
	$Lycan_intro = "<p>if you ask who is the most efficient push hero in the early stage, the answer will be lycan</p><p>if you ask who is the best carrier of necro book, the answer will be lycan</p><p>if you ask who has always been undermined yet still so strong, the answer will be lycan</p><p>Check out any dota record around 2013-14, you will find out, that lycan is almost always banned out at the first stage, if anyone dare to leave him to the opponent, they will pick him without any hesitation and push you all the way down in 20 mins, checkout TI4. There were lots of evidences there.</p><p>Is there any good solution to lycan? Let me think...maybe icefrog.</p>";
	$Mirana_intro = "<p>5 secs arrow, nothing could cheer up your teammate more than telling them that you got your enemy a 5 secs arrow, that's almost a gurantee to a kill in the early stage or a convincing team fight victory after 40 mins</p><p>Marina however is not just about the arrow, a professional mirana is an unsolvable problem and a rookie is an ATM. The balance between gank and farm is essential to a position 1 mirana, when you do everything right, mirana will be so strong from the very beginning to the end of the game, otherwise you may lose interest in dota.</p>";
	$Sven_intro = "<p>The toughest man, and with power from God, there is no tank in front of sven.</p><p>Back to 6.48 sven lina or sven leschrac are classic groups, you see them and hesitate for one sec, you die. Those hammers from sven are so strong and with blink dagger, madmask and bkb, you can not deal with him.</p>";
 ?>



